language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run --omit=*/migrations/* --source=admin,api manage.py test
after_success:
- codecov --token=711f2ba1-59bf-4dbc-95da-9d25ef91c932
deploy:
  provider: heroku
  api_key:
    secure: pwBBwenrjhguX/zN3KPGf0TLrNNnvPEbxvAfIbCkCx08kpOh9bn/tHHMu/HH7C2qzm+8fY2sPrMyuDOhRnPMCzTLoZ3DcVkSQnK+0i15/rxWhZCLch1UlxcUm8WDlEoPrJDcnyLqmfA+v1Dsbkpcs8TePq56DYcj7nbQXFJhioO2fHCYJH+QayxnJjwCWf6Q1fPkVbnRDHEe/08OKifTtDLrUeuZfd67r9RgKhQqDtbtofvViVV9TThDi7DNKbwSCiqHUiMpMCWU/NWOPOn94RAH8T2BAdZaoMsvB8DOX2/NENoiM3qWGN9ej/TNaORnrnv/SnnXDu4q+zemD+TQYnJM/n+GsvU6DuKrvRCWznUUn17SEH25fhwZLGZuNwa++p5Jh0Qab+1TQ6PjkrfAk01xAHyE2UOMHoFQMu5ILuTsWdvkpV0+YKHy4xoPD0hhSXhIk6MGIKk+wAX14hM4KlciG51SgQc/PjaQLXxChEyoDgH2ECCyP85m8UsigFJZxN/7ji50ZDQ+zxu4fu3sVqEiVW8PvGUG1+LONvCkWxcmMQzXXvFJMc2NSgXGhpuypvz7EkmDYQiH6WiMsZoYTHInab0yByV0tTNRORy0QOhTxjwQFUHs66QadT00ROby6TyIKK0m66dpj8u+SU2utZWPNwaLhIqqUjpx5LaOyVs=
