language: python
python: 3.6.6
node_js: '8'
services:
- postgresql
before_install:
- nvm install 8.11.3
- npm i -g npm
- npm install -g yarn
- node --version && npm --version && yarn --version && python --version
- export DJANGO_SETTINGS_MODULE=up.production_settings
install:
- pip install -r requirements.txt
- pip install codecov
- yarn install
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- python manage.py migrate
- python manage.py collectstatic --noinput
- ls
- coverage run --source=admin,api --omit=*/migrations/* manage.py test
after_success:
- codecov --token=$CODECOV_TOKEN
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: sCX/VCpkv0qkrjSoHera9MRnuyfe3dIEqux+X1mufaU3h7NzFR4m3vI45y+Gab2BfQDFyyZ4x28bpVGsncIVYWsefRIrtK6QeVmSuvMLX5M2jfSgayK9NRUucCrUG/a+uqVT5oA41VC6K1jT47B7Z6v7RFZr1177/ugXiEUF/eGC2NWYBdOIBaTCIfXBibZC+qIs6Na+qLDYDsRkLxfFHSdmAucTCXMPGWcUNKk3gNYP3ClXWvNqH22szOeOeJI7i4qOX6s7eJVnyON6iozk17bDyTB/K0nq5x1vmMRzULnk+mCgaekdjHr0SidlSJvw/riBFJUv0FJZptRbVYRn6T4koIRl5XZov2OWOzItpag5Fkc9X2W6EEGagNZU09LZLbGvKW7MEplF3S+7UqGu3X0OzmZSjCH3XBr48eVtISM1K2LQEQmWddEkaLTZWKxx3rx/s1LJFLgyJMEE44C3PjAfj/r9weAogSFgqe+NVxjYuBr1LxNMnq0yY11NUZSY7rUhZIv4V2lS1jf3qe3nRTOc7REiUuPIMRFokCPhtNfAK+Mf8uUf/aRsiizzEpLZKLAHCfR6P5iYcJIhEKZ17/sPoJ0KAGfYaq/uC0FwTjsjZYDLO298x5CGP+8RNxaNuuvC1+3HgCYRadZ2iRB1mLKA8aW2cnBWHDNU3V6aEFM=
  app: uspesnyprvnacek
env:
  global:
    secure: PHIo9ft4K/kxXBBNPHirqXnRJqACexh5RMb8E6VI03Bw2r1QEnw7f6bbpZWX6mUm9B7LM9sGuq7UC598ucgAmKjyYLDVREIo/xyIeimjAkE/2rrvexzzG96EkAKAJZcqOL9j1x/ywQa4ZqPKUNDP5pmwQuTJSiBsgucI2kIcbIaTv7DNJecoMqosMExtppItsRctCqRZnkFBrG1KYH8rgkDSbXCZsDLxYWL0TUZzZpzopVH4DfW3jof+bzu5F64mvsjuiwLu93QkOm0lvy5+P7SnTduzwifeoauVzU0fj1VWmPAAoTDSBVyxPjBrK9MkoCasFYu4ESAsiOLSVMzukzFIIUw+1Va3nLxWY2isF+D1NhlVxatpk5Xuo4OJxn41p1yrdGr9JFC1rJkQWduW4rirYM/ZJ0JSVmuX4wFVcsBp8gOe0SK9Wvr9Ks5P0RybmTfA9ZBTAexrobHW4bnQz/oXgC1uZ9vi545pjq4hlBhq3sB9iHgYlF2WYmH4fTf8H4x4SetBkKR4moPQqKHK9qnRyCc4DG+QZOu8uM1sLn6ho3mvrCA737DDgpRl2gLKrSe8xov8HfvhybctM0x6M6RV41ovDNOhH9SyuAi6/k2zBAxqoiW/yQLl/cS/HwSkTgviXrkw8WhIB/Wm4eioDridHIJaYytT3NiCXZcJdTk=
