language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run --omit=*/migrations/* --source=admin,api manage.py test
after_success:
- codecov --token=711f2ba1-59bf-4dbc-95da-9d25ef91c932
deploy:
  provider: heroku
  api_key:
    secure: DlploMkTCOVtG4kg09k7FoefF7ogUWAmXGj3ZO4MqddogYCHqLPr/XVSHG+Vzj5FlDoMw8cZSimUSX9uyKZMA8uC+o4syJorAJZS/bXLJKNuHFizf5T6wNS1AxunDhrvAvhbbcL+0oLqvXv5XtLeEeG6PXCKeup1CVaiaEHnE41SbF0ais85OeS/ctPL9J/K+xLAZLYoc5EcVyWQLtj1BzzjUYhRDwKuW2EjwBbVlFcLaFOXsNL5fa9ihApaPB0WlbDULQGOc41X81Aaalsq4jTg2c6tM5o8NzIIJ5/ogjyj0SGEPxwb9l2Igcw47c3buTJnLFrJiBx96a3ob+rVtrrmItqwaNwYluDMuZ5x0DVQ6SYKqoRjnfLgKV+hcdFfHCBYjCu+NCapH1TIvCI/xhqMstg44c22xZZfeHvYzmJLVgAfgNwbWeQuItReXlSww3l2WYFvRZdbu4fd9fUVp//Dgu7KSplByi7m7gk2rvjFpKjogSie1xNIAR8vFVeYqyYLcwTtk7Dd1vyN+xPOUIXVVaVB+C+v7RjGgb6ETSKrNysHxJXJkKXH6goM1ku2cBp/0xA7CXIl2tFL4SUhSoLyZsEBTLexCzhP7HrqSvCk1hzFA/+Y/kJ8PW8MhRT0hF2CVkz6IzlMu7ntIj4eFXl5kfrwfVvjRCRU0en/Znw=