language: python
python:
- '3.6'
node_js: 8
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
install:
- pip install -r requirements.txt
- pip install codecov
- cd frontend
- npm install
script:
- coverage run --omit=*/migrations/* --source=admin,api manage.py test
after_success:
- codecov --token=711f2ba1-59bf-4dbc-95da-9d25ef91c932
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: sCX/VCpkv0qkrjSoHera9MRnuyfe3dIEqux+X1mufaU3h7NzFR4m3vI45y+Gab2BfQDFyyZ4x28bpVGsncIVYWsefRIrtK6QeVmSuvMLX5M2jfSgayK9NRUucCrUG/a+uqVT5oA41VC6K1jT47B7Z6v7RFZr1177/ugXiEUF/eGC2NWYBdOIBaTCIfXBibZC+qIs6Na+qLDYDsRkLxfFHSdmAucTCXMPGWcUNKk3gNYP3ClXWvNqH22szOeOeJI7i4qOX6s7eJVnyON6iozk17bDyTB/K0nq5x1vmMRzULnk+mCgaekdjHr0SidlSJvw/riBFJUv0FJZptRbVYRn6T4koIRl5XZov2OWOzItpag5Fkc9X2W6EEGagNZU09LZLbGvKW7MEplF3S+7UqGu3X0OzmZSjCH3XBr48eVtISM1K2LQEQmWddEkaLTZWKxx3rx/s1LJFLgyJMEE44C3PjAfj/r9weAogSFgqe+NVxjYuBr1LxNMnq0yY11NUZSY7rUhZIv4V2lS1jf3qe3nRTOc7REiUuPIMRFokCPhtNfAK+Mf8uUf/aRsiizzEpLZKLAHCfR6P5iYcJIhEKZ17/sPoJ0KAGfYaq/uC0FwTjsjZYDLO298x5CGP+8RNxaNuuvC1+3HgCYRadZ2iRB1mLKA8aW2cnBWHDNU3V6aEFM=
  app: uspesnyprvnacek
  on:
    repo: rodlukas/cvut-fit-bibap-uspesnyprvnacek-code
env:
  global:
    secure: PaKtCRtHQ5wh2wolDMZCz4vE7+9/qwDEtx4dlAyIkAyaWcudmCdnmHI/ZQIaPzozRAldY1LwdPQ8RFI5+l1a3z4klO6fTb4IHxU1wlDmqRtnFR1vHOe9d5ED2g5vhSujOs23/2QPDSl2BoqJGg6JtxcDedNcYwKp7zKI6h6ddzsQnYvcSe2UvamZrWCsuZTb6AObsDq0HwOawZps4POwZKePKOCBdjl6J8+X+4S+qjQ04kChlxp80ux3UutI8Q2APJecDtxzSsKekCilyr6FImAnxkt9qQce0089QDiar7We5+eyP/9F1D55CHWEpC8u/SLweUn9ZZ3Jt8Yn4I3sV6PeTUL8P8pI7At5BqJsv93zn7dWUbWnQMognqz7TSbC2DrCdvf6ZRpFf+sodN+zzKx5PGegka7RUeshSb9nG6IR4ODmeEQ81CChfgw60xwqc3jtEnD//vpj6IylzQs1CIINOGnj8UvqfK+ILbAEailga8z6vA9pru+gEkfr8OhnOynvvSUM4kyLU7wBv0OWpoHjGCF3g9kwDuDtBFHqBeGhpeEQ1wKoOzKfflMlvUq0Z7qFMNNrQcFd9oVKRevZUpWhhIitivw7MrNn1/n9Ms0sDXLn2JZfZSknT/3GQMkXim65KKsS2FjD00BDW/hpFwDQKrXfJF3TO4ZQbwC67KY=
