language: python
python: 3.6.6
node_js: '8'
addons:
  postgresql: "9.6"
services:
- postgresql
before_install:
- nvm install 8.11.4
- npm i -g npm@^6.4.0
- npm install -g yarn@^1.9.0
- pip install pipenv
- node --version && npm --version && yarn --version && python --version && pipenv --version
- printf "//npm.fontawesome.com/:_authToken=${FONTAWESOME_TOKEN}\n" >> .npmrc
- source string_substitution.sh
install:
- pipenv install
- pipenv install codecov
- yarn install
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- source release-tasks.sh
- ls
- coverage run --source=admin,api --omit=*/migrations/* manage.py test
after_success:
- codecov --token=$CODECOV_TOKEN
notifications:
  email: false
  slack:
    secure: kNfvnpEk/TDNyqA6ueJ4cjpAtHKhoDp1sGLuhbj2KHYy4kivA1gDcWiF/Hdp9hAGlCiYVoMrY+dETyFY+zdwJtHbAolAEY0KGeb+Nwy1frU2aFSywbxC/CrnOHNCboTiOEpPivWpX5NAhypAlT0FTN5IFnYfbAkl+u0bnWIXbtxMDDxcV8PnN1IucKAvJeC6FPa7l4dPVmpe8dc0lsDPLD8713O+UG+I2d8CPP4yoYIgqdzLjd9zr05/albSXCXz+MjSfoA2QVfYRIpw0NyegMNdwChdBOTP9xds2D7P0xjLYhPVz98y2i4SyBzZcj+JXRYeA6Voi4WPAKeQHUJunA/dpEUZ/Rt2jIeNBAQxOUmRH+vmhKq+c9OwzeOfNUk7gZHxMFs3MEwPtDy62O9KmazzDDzr5hOCOqKboiGQONWt7Rp1yv4jzxlVZ6OxvzDF/COWnQLOIjVBzjSFIQH6LO5Gz/01ZQAqmtaZoWBb8xr3aebXDbrsPO6YSJZMyfXl4mRcMUGmGpEn1600jACpOKWED5NheRqIZnkSHBT/EurjFSXm7O+GztrPB14m3mBFn4o9xaQrkx35Zop0ZFf33w/UA+CeJ1jMdmArXF7RcNNcWQcZG8KbkIVj2qYUNY7sPjx+3K4B604jaAIj/Iwyoa+xQud0dR4zGZjcNzjRRPk=
deploy:
- provider: heroku
  api_key:
    secure: N6xpjlv4FHPGefx1CdoivRf3MfUwdggHD/U67EXUajzdtC67MY8Zl03+8MyfvDBbY/aPQ3CLsUlGMjxZ2oUeftPNfd0rgdcRXCT9/qEMpZFipe8YmBWQ4QMTPwQ2h4Ai1GYxq/Vf5psVvMiaMK1vLliu/7vFygm8327VhNpkOJPLAHreTDWAKyov8M08AXDiSG1YvcFfYIWkK43cJkEqyghhOQRwMbK6YzEhytmXCqZAGJQzfwcN9fEck3lQMsSqAiLpRCOR5tSWZytBr147xip6SwMl7+/R5aZJc7y+OjS3tLdQ39/IH7nFhfrgBcbrbwxIr1JNz9wfoA8LaYyAt8gTWdRmxwJctyq0MfOeKor191ExY24jzRglsAIXL/Q6/9QRoVmkAITLA5gc9BKtwM4nJvrLse48GK0Kh5ZJU6rEJpM+sy6IQer3Ke3Oywn9SWPBtUL+gUvNGfN1qwrQCZl4wZ7D4Qj85cl2JEom0O0Ddc0HzJxuuhA4e31KVPxAHRL2HIww2TNctShQtHG+TG+WM0/Wqw318FBQSU1lkp9KznirRdp1h32hZOFP1LsgFgBjkILaoOVGq2r1Hj/6YhVHHLHMapKIa0LhFnCvxIe589QB8tRt2FSbaus8aOyDSkryDCfAX4YaKLgWBsFq6OU0GiMVCFViz1SIaB0+DOI=
  app:
    master: uspesnyprvnacek-staging
  skip_cleanup: true
- provider: heroku
  api_key:
    secure: N6xpjlv4FHPGefx1CdoivRf3MfUwdggHD/U67EXUajzdtC67MY8Zl03+8MyfvDBbY/aPQ3CLsUlGMjxZ2oUeftPNfd0rgdcRXCT9/qEMpZFipe8YmBWQ4QMTPwQ2h4Ai1GYxq/Vf5psVvMiaMK1vLliu/7vFygm8327VhNpkOJPLAHreTDWAKyov8M08AXDiSG1YvcFfYIWkK43cJkEqyghhOQRwMbK6YzEhytmXCqZAGJQzfwcN9fEck3lQMsSqAiLpRCOR5tSWZytBr147xip6SwMl7+/R5aZJc7y+OjS3tLdQ39/IH7nFhfrgBcbrbwxIr1JNz9wfoA8LaYyAt8gTWdRmxwJctyq0MfOeKor191ExY24jzRglsAIXL/Q6/9QRoVmkAITLA5gc9BKtwM4nJvrLse48GK0Kh5ZJU6rEJpM+sy6IQer3Ke3Oywn9SWPBtUL+gUvNGfN1qwrQCZl4wZ7D4Qj85cl2JEom0O0Ddc0HzJxuuhA4e31KVPxAHRL2HIww2TNctShQtHG+TG+WM0/Wqw318FBQSU1lkp9KznirRdp1h32hZOFP1LsgFgBjkILaoOVGq2r1Hj/6YhVHHLHMapKIa0LhFnCvxIe589QB8tRt2FSbaus8aOyDSkryDCfAX4YaKLgWBsFq6OU0GiMVCFViz1SIaB0+DOI=
  app:
    master: uspesnyprvnacek
  skip_cleanup: true
