language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - coverage run --omit=*/migrations/* --source=admin,api manage.py test
after_success: coverage report