language: python
python: 3.6.6
node_js: '8'
addons:
  postgresql: "9.6"
services:
- postgresql
before_install:
- nvm install 8.11.4
- npm i -g npm@^6.4.0
- npm install -g yarn@^1.9.0
- pip install pipenv
- node --version && npm --version && yarn --version && python --version && pipenv --version
- printf "//npm.fontawesome.com/:_authToken=${FONTAWESOME_TOKEN}\n" >> .npmrc
- source string_substitution.sh
install:
- pipenv install
- pip install codecov
- yarn install
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- source release-tasks.sh
- ls
- coverage run --source=admin,api --omit=*/migrations/* manage.py test
after_success:
- codecov --token=$CODECOV_TOKEN
notifications:
  email: false
  slack:
    secure: kNfvnpEk/TDNyqA6ueJ4cjpAtHKhoDp1sGLuhbj2KHYy4kivA1gDcWiF/Hdp9hAGlCiYVoMrY+dETyFY+zdwJtHbAolAEY0KGeb+Nwy1frU2aFSywbxC/CrnOHNCboTiOEpPivWpX5NAhypAlT0FTN5IFnYfbAkl+u0bnWIXbtxMDDxcV8PnN1IucKAvJeC6FPa7l4dPVmpe8dc0lsDPLD8713O+UG+I2d8CPP4yoYIgqdzLjd9zr05/albSXCXz+MjSfoA2QVfYRIpw0NyegMNdwChdBOTP9xds2D7P0xjLYhPVz98y2i4SyBzZcj+JXRYeA6Voi4WPAKeQHUJunA/dpEUZ/Rt2jIeNBAQxOUmRH+vmhKq+c9OwzeOfNUk7gZHxMFs3MEwPtDy62O9KmazzDDzr5hOCOqKboiGQONWt7Rp1yv4jzxlVZ6OxvzDF/COWnQLOIjVBzjSFIQH6LO5Gz/01ZQAqmtaZoWBb8xr3aebXDbrsPO6YSJZMyfXl4mRcMUGmGpEn1600jACpOKWED5NheRqIZnkSHBT/EurjFSXm7O+GztrPB14m3mBFn4o9xaQrkx35Zop0ZFf33w/UA+CeJ1jMdmArXF7RcNNcWQcZG8KbkIVj2qYUNY7sPjx+3K4B604jaAIj/Iwyoa+xQud0dR4zGZjcNzjRRPk=
deploy:
- provider: heroku
  api_key:
    secure: Oq8ToF2x6JlO+Z+LpHSR7Jzo8UctJEby7sSkDY57hwVSpLXDJuTnPs4rXuzETwl66mnLZ52yp7rMwpyCYWHtwrZJxVGi4IPOG1wG5+qYe2N43PGEWP7mW0SYy5faXW1FzdaBwVQTxKuiTtRFnpwEAEqs1cZh7nPWvuoTqzyDZZZa7PJibKnSI1IpVYXQkZTu0wa/QwHmZzYpNVShpZs3clo/zqQ8ZaRIlL9LJ4IH9mR1utRwTVD76Y/9JeM7sBIfLlfQ+SYo2ZWaFF5NHYO+8URr9zjFFM1JbHXPpym6iF/nTVT4zq6UKMuf9wNwwyopvYDux2GQ40q63R7up1kZ+fyi2aV/NHIUmNFru9HhuTWjQfL2H4bICMQa6RHQ5rub9si5BTc1/ArvclkGC9LLpPruzPe4LKz6Ht+ni0Ql/tUnQ3BZHr7mCEFUqRf7zfnAF4E1NP8BTVTiX4qHNqtxBMslcw7Y6zauLuqqeng9KtwWzGViT5UQkQguBjFmB6W5xagfY+s6Je1c0LfdiGSk3PR3pFUm/z6Wjobvqc3+kxzRwffTLGRLLQyH5Uhjt9T1oQ8BkIcIshlcoeyOw3LETcqx1zG9tn7X8y2i0TX/SZ74jUyt4YRVuK6H5+5FW1zo3tfZRCESnTILHECO4apJMXHxhkf+UGRdER0kbh4RQpQ=
  app:
    master: uspesnyprvnacek-staging
  skip_cleanup: true
- provider: heroku
  api_key:
    secure: Oq8ToF2x6JlO+Z+LpHSR7Jzo8UctJEby7sSkDY57hwVSpLXDJuTnPs4rXuzETwl66mnLZ52yp7rMwpyCYWHtwrZJxVGi4IPOG1wG5+qYe2N43PGEWP7mW0SYy5faXW1FzdaBwVQTxKuiTtRFnpwEAEqs1cZh7nPWvuoTqzyDZZZa7PJibKnSI1IpVYXQkZTu0wa/QwHmZzYpNVShpZs3clo/zqQ8ZaRIlL9LJ4IH9mR1utRwTVD76Y/9JeM7sBIfLlfQ+SYo2ZWaFF5NHYO+8URr9zjFFM1JbHXPpym6iF/nTVT4zq6UKMuf9wNwwyopvYDux2GQ40q63R7up1kZ+fyi2aV/NHIUmNFru9HhuTWjQfL2H4bICMQa6RHQ5rub9si5BTc1/ArvclkGC9LLpPruzPe4LKz6Ht+ni0Ql/tUnQ3BZHr7mCEFUqRf7zfnAF4E1NP8BTVTiX4qHNqtxBMslcw7Y6zauLuqqeng9KtwWzGViT5UQkQguBjFmB6W5xagfY+s6Je1c0LfdiGSk3PR3pFUm/z6Wjobvqc3+kxzRwffTLGRLLQyH5Uhjt9T1oQ8BkIcIshlcoeyOw3LETcqx1zG9tn7X8y2i0TX/SZ74jUyt4YRVuK6H5+5FW1zo3tfZRCESnTILHECO4apJMXHxhkf+UGRdER0kbh4RQpQ=
  app:
    master: uspesnyprvnacek
  skip_cleanup: true
