language: python
python: 3.6.6
node_js: '8'
services:
- postgresql
before_install:
- nvm install 8.11.3
- npm i -g npm
- npm install -g yarn
- node --version && npm --version && yarn --version && python --version
- printf "//npm.fontawesome.com/:_authToken=${FONTAWESOME_TOKEN}\n" >> .npmrc
install:
- pip install -r requirements.txt
- pip install codecov
- yarn install
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- source release-tasks.sh
- ls
- coverage run --source=admin,api --omit=*/migrations/* manage.py test
after_success:
- codecov --token=$CODECOV_TOKEN
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: hykRzbKRAL7tBLOhy6wFRtMCISt+ZfLAk+Qy/OTZsLvhCLeh5VhQFmztzACAUdhwx/yfMgG63tCQMsGhlhTWI+RCrEEchqob+TdZowNSw0Ej92BfLV4PRyo1TPLQFCYehM2q0A/XfIBiUmBk6aRCohUlmo5EDHOtlx70SSb6/fwFmb5t/TXUlfZSJu2dxLnBIPiCsmk0THcp3lshSLBRV34QHKapjUwcjfj9BY0U9AH8+1TS0a4ikLfcFBEkWPejfpatQLXELHLgVao5lj4BBDFBjh26xQg3mAMBHkzk7ctONqm6JYhJjVSIEEC4eaDxvohy7XwKoF+bX7KvkQhThbIA0cpwErBUnfjR7wUadrQKl3QHE0geh7G28KTVD3lqhl2X63+XjyIFSeDebSixeL7Lp4ttPjpodJYWFpcAgJyPU95ohAQPTZMuR9N2uQQDyYZ26BI6daiJUkjp7lRrTAIxsDwo/1E/W+iaRB9/uD1+5t4E/9r6lVCaZ5IoB1XIC23IGoWQ/cBevhS/ABtxJeMCQXvgft+2OjRQPcTF4PzTREZ2lopFuekQ0IQ2fNGOLt+SimwF7VT1jGWXPLVtaAAK+1FwXokVAeIKamFb8sV8FbZJK1RmJxr4FfbdmLUN4/z6lD+F8CESWHNHwRkk9YmTvOa1GA1i2qWV7y0fWgA=
  app:
    master: uspesnyprvnacek
  skip_cleanup: true
env:
  global:
  - secure: PHIo9ft4K/kxXBBNPHirqXnRJqACexh5RMb8E6VI03Bw2r1QEnw7f6bbpZWX6mUm9B7LM9sGuq7UC598ucgAmKjyYLDVREIo/xyIeimjAkE/2rrvexzzG96EkAKAJZcqOL9j1x/ywQa4ZqPKUNDP5pmwQuTJSiBsgucI2kIcbIaTv7DNJecoMqosMExtppItsRctCqRZnkFBrG1KYH8rgkDSbXCZsDLxYWL0TUZzZpzopVH4DfW3jof+bzu5F64mvsjuiwLu93QkOm0lvy5+P7SnTduzwifeoauVzU0fj1VWmPAAoTDSBVyxPjBrK9MkoCasFYu4ESAsiOLSVMzukzFIIUw+1Va3nLxWY2isF+D1NhlVxatpk5Xuo4OJxn41p1yrdGr9JFC1rJkQWduW4rirYM/ZJ0JSVmuX4wFVcsBp8gOe0SK9Wvr9Ks5P0RybmTfA9ZBTAexrobHW4bnQz/oXgC1uZ9vi545pjq4hlBhq3sB9iHgYlF2WYmH4fTf8H4x4SetBkKR4moPQqKHK9qnRyCc4DG+QZOu8uM1sLn6ho3mvrCA737DDgpRl2gLKrSe8xov8HfvhybctM0x6M6RV41ovDNOhH9SyuAi6/k2zBAxqoiW/yQLl/cS/HwSkTgviXrkw8WhIB/Wm4eioDridHIJaYytT3NiCXZcJdTk=
  - secure: itf001mexI0C1h5u/B2ecdB359zHwGkws5Lw7wTB/eQV2Vr5IeaLwAp4JACzub/VpSYEpTZux0lXVPW1nWSWNHhVJNXYY5JQgq+5hKGbt56OYCrjE/1olAxfYpJNP2Yh12sDeww7h6TkFr37anaGK3ZhMmzKrHygQg2mPo+cvpgudvd9fOc/zqRDkX8+FPoFveEZzETEmIstRMYeAz1+nWaNfekqWPHvypItx8EqGBHO3fMEFF1qI2kzzlvwGQYS+lpFiX3pt5rB+wkntJjbcUirFfylvH3SF5zV/T1EuI3qbF1U7LDM9vPjwnqHPw7c1BFaFKTJTlpJOlqgKVNXb97qJJQgWvx8iQgH47Wf970Ro24qEfVjtSFy8BjMJPKeyNN3IHJ/Pf13Y5nQ/SvFL1r5G9ckIGePc44gMeSGnd2I7xko+CllZ5k87f4Sc6f1op9SRHqmWgzqzVQsy29NTUJXNzzuh2wbSLcZ80lLQpD1iKKTUxkgs0GsyWou59bKkCrVzewx7nWvXPzOwsZ9zf1v+V7t7bdxlN/g9oTMrG94XDIRl2Vpq4UHJUzYOZdeWszbMHaGaC0YU20rmdlJgoIy+5f723xfBRK+b6KoiM2kqXGow4NLzw3Zq3GjDyny0BK/p/xxaxNSGfke+L4mzjFNu+k060Wdey4BNT6L4Ow=
