language: python
python:
- '3.6'
before_install:
- export DJANGO_SETTINGS_MODULE=up.production-settings
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run --omit=*/migrations/* --source=admin,api manage.py test
- python manage.py --settings=up.production-settings
after_success:
- codecov --token=711f2ba1-59bf-4dbc-95da-9d25ef91c932
deploy:
  provider: heroku
  api_key:
    secure: j/JlibEVI/Ob0RZp19aDujF8VG9aLgUd2nIAcFb1/KQe2tGvG3xNdyr8NlrT10Xb9MQ7qKqCM6amlb1eNzMISU/EZb+8dP7e3nvgNw89SmeCQ72PMQj+4eC6Q7Qr5ZT4lKCZGnm/tVbw/4RMeEOJB2d9Qoj9p8F3tirUbSJDL5QztWxg0wvDfkWZiBUUd+1EBeD6Swk8tzZwNIhCg0W4rJg2kkeB3Eviqmg7acSEwqJ5PZYG3NKtBqd7OIg7UpauxSZeH4Q+DcJI4ibZ8UvYxc1WvI5+qaDu6m/7N+QqbQAdNrqSB3gnjwtu2zk/atu2uqqhlIjsTVGQSWKXRiKwwKIgfqE0DYhy5r2cTKH2++0Apkur0/9q4ZPxWA1mQAR4YOLN7//iPWmfPxVq5BDqmxkjW3I2M7sej9TqttFbWf9jMvfo3iPOrQ02ucrpS8UTI0lcR1nWT01SY+cv1HkoDTtUxeNPPFzDB4xiR4+ZdHMcQw01JzpGmkbEgAH3fsPjFomWHp9QHeHKQGhjSXJa4fI+umYzRHG7eAizBOP1NN6ECsQB/IQLF1Wpm+m3yPrfoag7fidbI1BiOD55lfGgsbjpy1jqhXVAXhC1D8tIfIRzsuEO6wIlnFjaD52nEbSu9Jz1qdhuPeFCbS6CzOhmN6Pc4UdHxFn1PTd31H8Cygo=
    app: uspesnyprvnacek