language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run --omit=*/migrations/* --source=admin,api manage.py test
after_success:
  - codecov --token=711f2ba1-59bf-4dbc-95da-9d25ef91c932