language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run --omit=*/migrations/* --source=admin,api manage.py test
after_success:
- codecov --token=711f2ba1-59bf-4dbc-95da-9d25ef91c932
deploy:
  provider: heroku
  api_key:
    secure: LF0q0DGCMevOr5gv/DhtP0WFzSGH6PNTAwBkQa5xmVMQu/I3olbxvfPW5q+dZj+pzRi21rlT2QDJwb1qypYKm/ECLgW5DkBZd/pXOrMORgaclawbrD6pb5BFj4FildJa3iVFclk72vsbZERnwQgL0CIQU9rPtnIXlTq5FJvfnLKi1U5pC/css8RYpi1ZX3qdKJ/jaC879kK4L/PwEfB0Mxw0LPB9F/M/NRafkJQuQWKEp2lCJK3vcm1lqKViYBU2ZdkTeTUJe/zgaA2ESHpIGoO0g5qtrCutH7i/7OUJHxIYPVVknfIX3xsacNwWsZXlOiAnG3JshpapvqplYI87ByRp6qaYZW+MhY9TEV+8b+0hzopU9zhD1odRhLvwN8JHL7NZSApKXnqoLhB8oWAvJerGae1D5BsNgWhkrXYsS92ytK9K85C5XkmNtnZrZ74CWYIK5ivqKW8XYu7uprCymjvJVBA7t1sqPDOhueJiJ9vv7NpEWuzNcu8IWedXX15mka8fpW2sSrQVJIizcLpK19Byxou+CzO8fDqx1wOHlxBUuSPwXoUetJzXv9LovouKvk9yYow4pRWaXt/FZsDvdHu2JfPu6M9N7X7gBjoL0v8NAFYMxjskeTdMdW2Db4KlxktgxwEG7H1uvTM/tYnZh1ZrqXTE0CpXllnE/tp8GXE=
